# -*- coding: utf-8 -*-
"""NLP_with_transformers_III.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jTNmB-hyCmGymYWNbEDyG5R2JG1A-VWR

# This is a work in progress

## Generative AI

Creating a body of text to traing a language model.
Text will come from a classic car forum powered by https://xenforo.com/.
The intent is to leverage generative AI to create a "virtual mechanic" to help maintain older cars that have a dwindling set of experts available to turn to.

### Create Enviornment
"""

!pip3 install pandas
!pip3 install numpy
!pip3 install requests
!pip3 install beautifulsoup4
!pip3 install transformers
!pip3 install torch

import pandas as pd

import numpy as np

import requests

from bs4 import BeautifulSoup

import re

import nltk
#nltk.download("all")
#nltk.download('punkt')
#nltk.download('stopwords')
#nltk.download('wordnet')
#nltk.download('vader_lexicon')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tag import pos_tag

from transformers import pipeline

# This seems to propagate credentials better from its own cell

from google.colab import drive
drive.mount('/content/drive')

"""## Database Schema

Table 1: Issues
<br>
*   Key Should be from pandas
*   Issue ID (Foreign Key) Should be the thread_id
*   Issue Should be the thread title
*   Short Description Should be from the thread post
*   Keywords: Should be from the thread post

Table 2: Solutions
<br>
*   Key Should be from pandas
*   Issue ID (Foreign Key) Should be the thread_id
*   Detailed Solution Should be from the thread posts
*   Keywords Should be from the thread posts

Table 3: Notes
<br>
*   Key Should be from pandas
*   Issue ID (Foreign Key) Should be taken from the thread_key
*   Unstructured Note Content Should be from the thread posts

## Create corpus
"""

# Create list of URLs to seach and parse

import pandas as pd

threads = 100

import pandas as pd

data = []

def create_urls(threads, page_number=1):
    base_url = 'https://e9coupe.com/forum/threads/'
    # Iterate over thread IDs to generate URLs
    for thread_id in range(1, threads + 1):
        thread_url = f"{base_url}{thread_id}"
        data.append({'thread_id': thread_id, 'thread_url': thread_url})

# Call the function with the correct parameter
create_urls(threads)  # Using the 'threads' variable

# Convert the list of dictionaries into a DataFrame
df_urls = pd.DataFrame(data)

# Display the resulting DataFrame
df_urls.head()

# Process URLs into a df of thread ids and thread titles

pages = 1

data = []

df_threads = pd.DataFrame()

def fetch_thread_data(df):
    for index, row in df.iterrows():
        thread_id = row['thread_id']
        url = row['thread_url']
        for i in range(1, pages + 1):
            page_url = f"{url}/?page={i}"  # Construct the page URL
            response = requests.get(page_url)
            if response.status_code == 200:
                soup = BeautifulSoup(response.text, 'html.parser')
                title = soup.find('title').get_text()
                thread_title = title.split('|')[0].strip()  # Extract the thread title

                data.append({'thread_id': thread_id, 'thread_title': thread_title, 'thread_url': page_url})

    return data

# Fetch thread data
data = fetch_thread_data(df_urls)

# Convert the list of dictionaries into a DataFrame
df_threads = pd.DataFrame(data)

# Display the resulting DataFrame
df_threads.head()

# Extract the inital content when the thread was created.
# This text will be used to create a short description

def fetch_first_post_content(df):
    data = []

    for thread_id, url in zip(df['thread_id'], df['thread_url']): # ensures pairing
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')

        first_post = soup.find('article', class_='message-body')
        post_content = first_post.get_text(strip=True)

        data.append({'thread_id': thread_id, 'thread_first_post': post_content})

    return data

# Fetch first post content and convert to DataFrame
data = fetch_first_post_content(df_threads)
first_post_df = pd.DataFrame(data)

# Casting the values I want to join on
df_threads['thread_id'] = df_threads['thread_id'].astype(int)
first_post_df['thread_id'] = first_post_df['thread_id'].astype(int)

# Update the df
df_threads = pd.merge(df_threads, first_post_df, on='thread_id', how='left')

# Display the resulting DataFrame
df_threads.head()

# This is a summarization of the initial thread post

from transformers import T5ForConditionalGeneration, T5Tokenizer

# Initialize the T5 tokenizer and model
tokenizer = T5Tokenizer.from_pretrained('t5-small')
model = T5ForConditionalGeneration.from_pretrained('t5-small')

def summarize_text(df):

    thread_first_post_summary = []  # Initialize the list to hold summaries
    for thread_id, text in zip(df['thread_id'], df['thread_first_post']): # ensures pairing

        # Prefixing the input text with "summarize: " as T5 expects
        inputs = tokenizer.encode("summarize: " + text, return_tensors="pt", truncation=True, max_length=512)
        summary_ids = model.generate(inputs, max_length=150, length_penalty=2.0, num_beams=4, early_stopping=True)

        # Decode the generated ids to get the summary text
        summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

        # Append the tuple containing thread_id and summary to the list
        thread_first_post_summary.append((thread_id, summary))

    return thread_first_post_summary

# Fetch first post content and convert to DataFrame
data = summarize_text(df_threads)
df_short_desc = pd.DataFrame(data, columns=['thread_id', 'thread_first_post_summary'])

# Merge the summarized_df with df_threads on the 'thread_id' column
df_threads = pd.merge(df_threads, df_short_desc, on='thread_id', how='left')

# Display the resulting DataFrame
df_threads.head()

# Need keywords from the initial thread post
# Keyword extraction with BERT
from transformers import BertTokenizer, BertModel

import torch

# Load pre-trained BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Function to extract keywords using BERT
def bert_extract_keywords(text, tokenizer, model, top_n=5):
    # Tokenize and encode the text
    inputs = tokenizer.encode_plus(text, add_special_tokens=True, return_tensors="pt", truncation=True, max_length=512)
    input_ids = inputs['input_ids'][0]

    # Get the embeddings from the last hidden layer
    with torch.no_grad():
        outputs = model(**inputs)
    embeddings = outputs.last_hidden_state.squeeze(0)

    # Compute word importance by summing up the embeddings
    word_importance = torch.sum(embeddings, dim=1)

    # Get the indices of the top n important words
    top_n_indices = word_importance.argsort(descending=True)[:top_n]

    # Filter out indices that are out of range of input_ids
    top_n_indices = [idx for idx in top_n_indices if idx < len(input_ids)]

    # Decode the top n words
    keywords = [tokenizer.decode([input_ids[idx]]) for idx in top_n_indices]

    return keywords

# df_threads['keywords'] = bert_extract_keywords(df_threads['summary'],tokenizer, model)
df_threads['thread_first_post_keywords'] = df_threads['thread_first_post_summary'].apply(lambda x: bert_extract_keywords(x, tokenizer, model))

# Display the resulting DataFrame
df_threads.head()

#Process threads and fetch all post data'

# As written this will fetch all the posts on the first page, which is 20
# This needs to be updated to iterate through all page values (1 through n)

def fetch_and_parse_thread(df):
    post_data = []
    processed_posts = set()
    for index, row in df.iterrows():
        response = requests.get(row['thread_url'])
        soup = BeautifulSoup(response.text, 'html.parser')
        articles = soup.find_all('article', class_='message--post')  # Correct class name as example
        for article in articles:
            post_id = article.get('id', 'N/A')
            numeric_post_id = re.findall(r'\d+', post_id)[0] if re.findall(r'\d+', post_id) else 'N/A'

            if numeric_post_id not in processed_posts:
                processed_posts.add(numeric_post_id)
                content = article.find('div', class_='bbWrapper').get_text(strip=True)
                #timestamp = article.find('time', class_='u-dt').get_text(strip=True) if article.find('time', class_='u-dt') else 'N/A'
                #post_number_element = article.find('ul', class_='message-attribution-opposite').find('li').find_next_sibling('li')
                #post_number = post_number_element.get_text(strip=True) if post_number_element else 'N/A'
                #post_number = post_number.lstrip('#') if post_number != 'N/A' else post_number

                post_data.append({
                    'thread_id': row['thread_id'],  # Corrected to use row's data
                    'post_id': numeric_post_id,
                    #'post_number': post_number,
                    'post_raw': content
                })

    return pd.DataFrame(post_data, columns=['thread_id', 'post_id','post_raw'])

# Fetch thread URLs and titles, and store in a DataFrame
df_posts = fetch_and_parse_thread(df_threads)

# Display the resulting DataFrame
df_posts.head()

# This is a summarization of all posts for a given thread

# Count the number of unique threads to ensure I dont drop any
print(df_posts['thread_id'].nunique())

# Contactinate all posts per thread
aggregated_posts = df_posts.groupby(['thread_id'])['post_raw'].apply(lambda x: ' '.join(x)).reset_index(name='post_concat')

df_threads = df_threads.merge(aggregated_posts, on=['thread_id'], how='left')

# Display the resulting DataFrame
df_threads.head()

"""### Pre-process the text

### Short Description

### Summarization
Very difficult to find a winning strategy here that can accomidate both long and short length text blocks.

**Extractive Summarization**
<br>
Pros:
<br>
Good with Raw Text: Extractive methods can work directly with raw, unstructured text, as they mainly focus on selecting key sentences or phrases without needing deep linguistic processing.
Straightforward Implementation: These methods do not require complex preprocessing like tokenization or lemmatization, simplifying their implementation.
<br>
Cons:
<br>
Limited Depth in Understanding: While they can handle raw text, they may not fully capture the nuanced meaning, especially when the text contains complex structures or unorthodox language use.
Less Effective with Poorly Structured Text: In cases where the text is poorly structured or highly informal, extractive summarization might struggle to identify the main points effectively.
<br>
<br>


**Abstractive Summarization** (like sshleifer/distilbart-cnn-12-6)
<br>
Pros:
<br>
Advanced Processing Capabilities: Abstractive models, especially those based on transformer architectures, are designed to handle and interpret raw text, capturing deeper linguistic and contextual nuances.
Higher Tolerance for Unstructured Text: These models can manage unstructured or informal text by understanding and then rephrasing it in a more coherent and structured summary.
<br>
Cons:
<br>
Dependence on Preprocessing for Optimal Performance: While they can process raw text, the quality of the output can be significantly improved with proper tokenization and lemmatization, especially for complex texts.
Potential Overhead: Requires more computational resources to process and understand raw text, which might be more efficiently handled with some level of preprocessing.
<br>
<br>
**Hybrid Summarization**
<br>
Pros:
<br>
Flexibility in Text Processing: Combining extractive and abstractive methods allows for handling both raw and preprocessed text, adapting to the text's structure and complexity.
Balanced Approach: Can leverage the strengths of extractive methods in handling raw text for identifying key points, while using abstractive techniques for generating a coherent summary.
<br>
Cons:
<br>
Complex Preprocessing Requirements: The need to integrate both extractive and abstractive approaches may necessitate more sophisticated preprocessing strategies to optimize performance.
Potential for Processing Inefficiencies: The combined approach might lead to redundancies or inefficiencies in processing, especially if the text is either too raw or overly preprocessed.
<br>
<br>
After attempting sshleifer/distilbart-cnn-12-6 I found it had a character limit (1024) that is too restrictive for my needs. However, T5 has no limits and is what Ill be trying.
"""

# This is a summarization of all posts for a given thread

from transformers import T5ForConditionalGeneration, T5Tokenizer

# Initialize the T5 tokenizer and model
tokenizer = T5Tokenizer.from_pretrained('t5-small')
model = T5ForConditionalGeneration.from_pretrained('t5-small')

def summarize_text(df):
    sum_text = []  # Initialize the list to hold summaries
    for text in df['post_concat']:
        # Ensure the text is a string and not empty
        #if not isinstance(text, str) or not text.strip():
        #    sum_text.append("")  # Append an empty string for non-valid entries
        #   continue

        # Prefixing the input text with "summarize: " as T5 expects
        inputs = tokenizer.encode("summarize: " + text, return_tensors="pt", truncation=True, max_length=512)
        summary_ids = model.generate(inputs, max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True)

        # Decode the generated ids to get the summary text
        summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

        sum_text.append(summary)

    return sum_text

df_threads['post_summary'] = summarize_text(df_threads)

# Display the resulting DataFrame
df_threads.head()

"""### Keywords

Raw text vs pre-processed
Using Pre-Processed Data

Fine-Tuning BERT or Similar Models
Pros:

Effective with Preprocessed and Raw Text: Can handle both preprocessed (for cleaner, more focused analysis) and raw text (to capture nuances and specific jargon).
Good with Varied Text Lengths: Capable of managing both short and long texts, though long texts might need to be segmented due to token limits.
Cons:

Token Limitations for Long Texts: BERT has a token limit (512 tokens), necessitating additional processing for longer texts.
Resource-Intensive: Requires significant computational resources, especially for processing and fine-tuning on large datasets.
2. Using GPT-3 for Response Generation
Pros:

Adaptable to Both Text Types: Can generate responses based on both preprocessed and raw text, utilizing the context effectively.
Handles Long Text Well: GPT-3's architecture allows it to handle longer sequences of text better than many other models, making it suitable for detailed responses.
Cons:

Context Dilution in Long Texts: Might lose context in very long text sequences, affecting response relevance.
Operational Cost and Accessibility: Using GPT-3, particularly at scale, can be expensive and subject to usage constraints.
3. Hybrid Approach (Combining Fine-Tuned BERT and GPT-3)
Pros:

Versatility with Text Types: Combines BERT's analytical strength (which can handle both preprocessed and raw text) with GPT-3’s generative capabilities.
Effective with All Text Lengths: Can manage short texts efficiently and long texts through a combination of BERT's analytical precision and GPT-3's generative scope.
Cons:

Integration Complexity: Managing and integrating two systems, especially ensuring coherence between them, adds complexity.
High Resource Requirement: Both models are resource-intensive, which could be a significant factor, particularly for processing large datasets.
Additional Consideration: Preprocessed vs. Raw Text
Preprocessed Text: While cleaner and more structured, may lose crucial context or technical terms, which can be pivotal in a specialized domain like automotive discussions.
Raw Text: Retains all original information, including specific jargon and nuances, but is more challenging to process due to irregularities and noise.
"""

from transformers import BertTokenizer, BertModel

import torch

# Load pre-trained BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Function to extract keywords using BERT
def bert_extract_keywords(text, tokenizer, model, top_n=5):
    # Tokenize and encode the text
    inputs = tokenizer.encode_plus(text, add_special_tokens=True, return_tensors="pt", truncation=True, max_length=512)
    input_ids = inputs['input_ids'][0]

    # Get the embeddings from the last hidden layer
    with torch.no_grad():
        outputs = model(**inputs)
    embeddings = outputs.last_hidden_state.squeeze(0)

    # Compute word importance by summing up the embeddings
    word_importance = torch.sum(embeddings, dim=1)

    # Get the indices of the top n important words
    top_n_indices = word_importance.argsort(descending=True)[:top_n]

    # Filter out indices that are out of range of input_ids
    top_n_indices = [idx for idx in top_n_indices if idx < len(input_ids)]

    # Decode the top n words
    keywords = [tokenizer.decode([input_ids[idx]]) for idx in top_n_indices]

    return keywords

df_threads['post_keywords'] = df_threads['post_summary'].apply(lambda x: bert_extract_keywords(x, tokenizer, model))

# Display the resulting DataFrame
df_threads.head()

# Export and save result
df_threads.to_csv('/content/drive/MyDrive/e9/nlp/df_threads.csv', index=False)

"""####Table 1: Issues

*   ID (Unique ID)
*   Issue
*   Short Description
*   Keywords



"""

#Table 1 Issues

#*   Key Should be from pandas
#*   Issue ID (Foreign Key) Should be taken from the thread_id
#*   Issue Should be the thread title
#*   Short Description Using the thread title for now. Should be the post of the originating thread
#*   Keywords: Should be from the thread post

# Table 1
df_table_1 = df_threads[['thread_id','thread_title','thread_first_post_summary','thread_first_post_keywords']]

"""####Table 2: Solutions

*   ID (Unique Note ID)
*   Issue
*   Issue ID (Foreign Key linking to ID in Issues table)
*   Solution

"""

#Table 2
#*   Key Should be from pandas
#*   Issue Should be the thread title
#*   Issue ID (Foreign Key) Should be taken from the thread_key
#*   Detailed Solution Should be the concatinated post_raw per thread_id
#*   Keywords Should be from be the concatinated post_raw per thread_id

df_table_2 = df_threads[['thread_title','thread_id','post_concat','post_keywords']]

"""####Table 3: Notes

Key Should be from pandas
Issue ID (Foreign Key) Should be taken from the thread_key
Unstructured Note Content Should be from the thread posts
"""

# Table 3: Notes

#*   Key Should be from pandas
#*   Issue ID (Foreign Key) Should be taken from the thread_key
#*   Unstructured Content: Should be from the raw thread posts

df_table_3 = df_threads[['thread_id','post_concat']]

"""What if I processed a complete auto repair guide to train on ??

ChatGPT
Training a keyword extraction model on a complete auto repair guide or similar domain-specific text is an excellent idea, especially if your goal is to improve the relevance and accuracy of keyword extraction for automotive discussions. Here's how you can approach this:

Domain-Specific Corpus: Obtain a corpus of domain-specific texts, such as auto repair manuals, guides, or technical documents. This corpus should contain text that is closely related to the automotive domain and covers various aspects of auto repair, maintenance, and troubleshooting.

Preprocessing: Preprocess the text data, similar to what you did with your forum data. This includes tokenization, stop word removal, lemmatization, and any other necessary cleaning steps.

Keyword Labeling: Manually label or annotate the relevant keywords in this domain-specific text. You can do this by identifying words or phrases that are highly relevant to specific topics, parts, or procedures in the auto repair domain. This labeled data will serve as your training dataset.

Training a Keyword Extraction Model: Utilize a machine learning or NLP model to train on this labeled dataset. You can explore different models, including traditional machine learning models (e.g., SVM, Random Forest) or deep learning models (e.g., BERT with fine-tuning). The model's objective should be to predict or extract keywords based on the labeled examples.

Evaluation: After training the model, evaluate its performance using appropriate metrics. You can use metrics such as precision, recall, and F1-score to assess how well the model identifies keywords in the automotive domain.

Fine-Tuning: Depending on the evaluation results, you may need to fine-tune the model to improve its keyword extraction accuracy. This can involve adjusting hyperparameters, increasing the amount of training data, or refining the labeling process.

Integration: Once you have a well-trained keyword extraction model, you can integrate it into your project. You can use this model to extract keywords from the automotive forum discussions, improving the relevance and specificity of the extracted keywords.

Continuous Learning: Keep in mind that language and terminology in the automotive field can evolve over time. It's essential to periodically update and retrain your keyword extraction model to stay current with the latest industry terminology and trends.

By training a model on a domain-specific corpus, you can leverage the specialized knowledge contained in auto repair guides to enhance the accuracy and context-awareness of your keyword extraction process. This approach should help you generate more relevant and meaningful keywords for automotive discussions, ultimately improving the quality of your analysis and insights.

## Model creation and training

The project will use the GPT-2 pre-trained model. This choice is due to the lower cost vs GPT-3 and higher. The model will be supplemented with very specific data that is was not included in the training of GPT-2. An overview of the project is as follows:
"""

# First attempt, using GPT2

from transformers import GPT2LMHeadModel, GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

# Set tokenizer padding token with 'left' padding
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

# Define your prompt for generating a pizza recipe
prompt = "How do I replace the water pump on a 1973 BMW 3.0cs ?"

# Encode the prompt
inputs = tokenizer.encode(prompt, return_tensors='pt', padding='max_length', max_length=100, truncation=True)

# Generate text using the model
outputs = model.generate(inputs, max_length=200, num_return_sequences=1, pad_token_id=tokenizer.eos_token_id)

# Decode and print the generated recipe
generated_recipe = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(generated_recipe)

"""## Parking Lot

## Topic Modeling with Latent Dirichlet Allocation (LDA) in NLP
https://towardsdatascience.com/latent-dirichlet-allocation-lda-9d1cd064ffa2

## Load tables into Snowflake
"""

# Old code on determining post vs thread



        # Parse the HTML content of the page
#        soup = BeautifulSoup(page.content, "html.parser")
#        results = soup.find_all('div', class_='contentRow-main')

#        for result in results:
#            title_element = result.find('h3', class_='contentRow-title')
#            if title_element and title_element.find('a'):
#                title = title_element.get_text(strip=True)
#                url = title_element.find('a')['href']

                # Check if it's a thread or a post
#                post_info = result.find('div', class_='contentRow-minor').get_text(strip=True)
#                if "Thread" in post_info:
#                    type = "Thread"

 #                   print(f"Title: {title}, URL: {url}, Type: {type}")
 #                   print('--------------------------------------------------')
                # Append the information to a list
#                    url = 'https://e9coupe.com'+url
#                    thread_urls.append({'url': url})
#                    #thread_urls.append({'title': title, 'url': url, 'type': type})


# Create a DataFrame for the URLs
#df_threads = pd.DataFrame(thread_urls)